In [61]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [62]:
df = pd.read_csv('Breast_cancer_dataset.csv')

In [63]:
df.keys()

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [64]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

In [67]:
scalar = StandardScaler()
scaled_df = scalar.fit_transform(df)

In [68]:
scaled_df

array([[-0.23640517,  1.29767572,  1.09706398, ...,  2.29607613,
         2.75062224,  1.93701461],
       [-0.23640344,  1.29767572,  1.82982061, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 0.43174109,  1.29767572,  1.57988811, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [-0.23572747,  1.29767572,  0.70228425, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [-0.23572517,  1.29767572,  1.83834103, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-0.24240586, -0.77060855, -1.80840125, ..., -1.74506282,
        -0.04813821, -0.75120669]], shape=(569, 32))

In [69]:
from sklearn.decomposition import PCA

In [70]:
pca = PCA(n_components=5)

In [71]:
data_pca = pca.fit_transform(scaled_df)

In [72]:
data_pca

array([[ 9.21672415,  2.13674957, -0.9966659 , -3.70198913,  1.25475921],
       [ 2.65124379, -3.77074095, -0.55431876, -1.13341639, -0.55363383],
       [ 5.90069721, -1.01091626, -0.46784118, -0.93375533,  0.19457431],
       ...,
       [ 1.5257542 , -1.95055191,  0.43706779,  2.09293037, -1.82408843],
       [10.39583236,  1.87122919, -1.8083534 ,  2.15937042, -0.20577947],
       [-5.50787608, -0.76780509,  1.35516174,  2.37187262,  0.13446934]],
      shape=(569, 5))

In [73]:
pca.explained_variance_

array([13.94854707,  5.74139697,  2.86996767,  2.00265173,  1.66205541])

In [74]:
pca.explained_variance_ratio_

array([0.43512603, 0.17910333, 0.08952887, 0.06247288, 0.05184795])

In [75]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [76]:
pca.components_

array([[ 2.20132922e-02,  2.16835592e-01,  2.16404027e-01,
         1.03705734e-01,  2.24541449e-01,  2.18006681e-01,
         1.37491085e-01,  2.31310529e-01,  2.51115412e-01,
         2.55161269e-01,  1.32845487e-01,  5.77855009e-02,
         2.01029857e-01,  1.54622802e-02,  2.05740326e-01,
         1.98169346e-01,  1.13755627e-02,  1.61834101e-01,
         1.45749613e-01,  1.76263374e-01,  3.82549061e-02,
         9.50271520e-02,  2.25596809e-01,  1.05058041e-01,
         2.33635556e-01,  2.22021699e-01,  1.25187917e-01,
         2.04288155e-01,  2.22927498e-01,  2.46161454e-01,
         1.20461432e-01,  1.26524229e-01],
       [-3.23675385e-02, -7.70349679e-02, -2.26045159e-01,
        -5.85866386e-02, -2.07124743e-01, -2.22896736e-01,
         1.89042427e-01,  1.58966989e-01,  6.81753131e-02,
        -2.67021580e-02,  1.93525229e-01,  3.67580893e-01,
        -9.75765544e-02,  9.07763943e-02, -8.10821756e-02,
        -1.44070567e-01,  2.04143726e-01,  2.38631448e-01,
         2.02849087e-01,  1.36670824e-01,  1.85720018e-01,
         2.83830266e-01, -2.12407724e-01, -4.51637273e-02,
        -1.92093619e-01, -2.11595119e-01,  1.72729248e-01,
         1.48266924e-01,  1.03591165e-01, -1.78544102e-03,
         1.42764783e-01,  2.76795104e-01],
       [ 9.79034765e-02, -1.04562282e-01, -2.70960919e-04,
         5.72563664e-02, -8.92353233e-04,  3.78086010e-02,
        -1.01731206e-01, -6.77958522e-02,  9.54202955e-03,
        -1.90130290e-02, -4.10026004e-02, -2.27916725e-02,
         2.73397922e-01,  3.58510252e-01,  2.72133678e-01,
         2.25301273e-01,  3.03110258e-01,  1.57786485e-01,
         1.80524945e-01,  2.27440966e-01,  2.79513196e-01,
         2.12002163e-01, -3.92101237e-02, -5.03523944e-02,
        -3.98885596e-02, -2.39446769e-03, -2.57202911e-01,
        -2.29455830e-01, -1.65984489e-01, -1.62801516e-01,
        -2.71611002e-01, -2.29383010e-01],
       [ 2.73002436e-02,  9.82144424e-02, -5.12570734e-02,
         5.99486560e-01, -5.20450016e-02, -6.18337132e-02,
        -1.49217429e-01, -4.05240345e-02, -2.80968020e-02,
        -7.07320983e-02, -5.99098158e-02, -4.62896088e-02,
        -9.08512521e-02,  3.73811948e-01, -8.41887597e-02,
        -1.05458543e-01, -2.01273760e-02,  1.89547579e-02,
        -1.04376156e-02, -7.46243121e-02, -2.66886150e-02,
        -1.76820748e-02, -2.45157621e-02,  6.27974557e-01,
        -2.38266465e-02, -3.39927037e-02, -1.06674431e-02,
         7.55251061e-02,  5.80622927e-02, -1.68474575e-02,
         3.59086370e-02,  6.72937174e-02],
       [ 9.11709186e-03,  8.06796770e-02, -4.20195424e-02,
         2.01578999e-02, -4.18314480e-02, -1.42924688e-02,
         3.67699325e-01, -1.70367241e-02, -8.97214089e-02,
         4.13796470e-02,  3.03753667e-01,  4.58901848e-02,
         1.57652281e-01,  1.80668561e-01,  1.22949568e-01,
         1.28256422e-01,  2.44856866e-01, -2.79436537e-01,
        -3.50100221e-01, -1.86627823e-01,  2.58846373e-01,
        -2.56859065e-01, -1.65141423e-03,  6.04630385e-02,
        -1.40254896e-02,  2.12428772e-02,  3.21004394e-01,
        -1.33442184e-01, -1.97065669e-01, -4.89799577e-02,
         2.35422546e-01, -1.01783159e-01]])

In [77]:
pca_df = pd.DataFrame(
    pca.components_[:2],
    columns=df.columns,
    index=['PC1', 'PC2']
)

pca_df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
PC1,0.022013,0.216836,0.216404,0.103706,0.224541,0.218007,0.137491,0.231311,0.251115,0.255161,...,0.225597,0.105058,0.233636,0.222022,0.125188,0.204288,0.222927,0.246161,0.120461,0.126524
PC2,-0.032368,-0.077035,-0.226045,-0.058587,-0.207125,-0.222897,0.189042,0.158967,0.068175,-0.026702,...,-0.212408,-0.045164,-0.192094,-0.211595,0.172729,0.148267,0.103591,-0.001785,0.142765,0.276795

In [78]:
X = df.drop(['diagnosis'], axis=1)
y = df['diagnosis']

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [80]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

c:\Users\Rafi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [81]:
y_pred = model.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.956140350877193

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.99      0.97        71
           1       0.97      0.91      0.94        43

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114